### ISSUE TITLE
regex supporting problem

### ISSUE THREAD

**Issue by qingliangcn** [rvirding/leex#4]
Erlang Version: R18.3

when i use this regex in leex(*.xrl):

```
\/\*(\*(?!\/)|[^*])*\*\/
```

i got this error:

```
 bad regexp `illegal character ?'
```

**Comment by qingliangcn** [comment]
sorry for not reading the close post

**Comment by rvirding** [comment]
The reason you are getting an error is that the patterns supported by leex are not the same as for instance Perl. They are a set of patterns which can be compiled to an efficient DFA. This is impossible to do with very many of the options in Perl regexs. It is this feature of being able to generate a DFA which makes this type of tool efficient to use. For a description of what is available see the [leex documentation](http://erlang.org/doc/man/leex.html).

`?` only means matches 0 or 1 of the preceding expressions.
