### ISSUE TITLE
regex for regex in leex

### ISSUE THREAD

**Issue by qingliangcn** [rvirding/leex#5]
in stackoverflow i found a regex for regex:

```
/^((?:(?:[^?+*{}()[\]\\|]+|\\.|\[(?:\^?\\.|\^[^\\]|[^\\^])(?:[^\]\\]+|\\.)*\]|\((?:\?[:=!]|\?<[=!]|\?>)?(?1)??\)|\(\?(?:R|[+-]?\d+)\))(?:(?:[?+*]|\{\d+(?:,\d*)?\})[?+]?)?|\|)*)$/
```

but leex doesnt support ^and$ in match rules, is there anyway else to doing this ?

**Comment by rvirding** [comment]
No, `^` and `$` aren't supported yet but there is so much in that regex which is not supported so it doesn't matter. :-) See my reply to the preceding issue. It boils down to that leex does not support Perl regexs for a very good reason.

**Comment by qingliangcn** [comment]
thanks ...
