### ISSUE TITLE
Parametrized xrl file ?

### ISSUE THREAD

**Issue by crownedgrouse** [rvirding/leex#6]
How to declare for instance a tokenizer where separators are declared in beginning of file to parse ?
I think to EDIFACT or ANSI X12 EDI files where separators are declared in beginning.
It could be nice to pass value of a macro while running lexer, or a syntax to pick characters in some position or catching ereg on file itself, instead having to do templates to generate xrl file and compile at runtime.

**Comment by crownedgrouse** [comment]
Hello Robert, any thought on this?

**Comment by rvirding** [comment]
No, sorry I don't have any.

**Comment by crownedgrouse** [comment]
There is no problem that lack of solution cannot resolve.
